server:
  port: 8000

spring:
  application:
    name: micro-commerce-api-gateway

eureka:
  client:
    service-url:
      defaultZone: http://service-discovery:8761/eureka
    register-with-eureka: true
    fetch-registry: true